# fly.toml app configuration file generated for resolve-account-issue on 2024-05-28T14:13:32+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'resolve-account-issue'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
